version: '3.3'

services:
    walletscrypto:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports: 
            - "4000:4000"
            - "4001:4001"
        volumes:
            - ../SSLCertificates/WalletsCrypto:/certificates/